matrix:
  include:
    - name: "Ubuntu 16.04 with Python 2 bindings"
      os: linux
      dist: xenial
      language: c
      install:
        - "sudo apt-get install autoconf libtool build-essential"
        - "python2 -m pip install cffi sklearn catboost==0.20 xgboost==0.82 --user"
      script:
        - "./bootstrap.sh"
        - "PYTHON=python2 ./configure"
        - "make clean"
        - "make"
        - "python2 bindings/python/setup.py test"
        - "python2 bindings/python/example.py"

    - name: "Ubuntu 16.04 with Python 3 bindings"
      os: linux
      dist: xenial
      language: python
      python: "3.6"
      install:
        - "sudo apt-get install autoconf libtool build-essential"
        - "pip install cffi sklearn catboost==0.20 xgboost==0.82"
      script:
        - "./bootstrap.sh"
        - "PYTHON=python3 ./configure"
        - "make clean"
        - "make"
        - "python3 bindings/python/setup.py test"
        - "python3 bindings/python/example.py"

    - name: "macOS 11.3 with Python 2 bindings"
      os: osx
      osx_image: xcode12.5
      language: c
      install:
        - "brew install argp-standalone"
        - "python -m pip install cffi sklearn catboost==0.20 xgboost==0.82 --user"
      script:
        - "./bootstrap.sh"
        - "./configure"
        - "make clean"
        - "make"
        - "python bindings/python/setup.py test"
        - "python bindings/python/example.py"
