matrix:
  include:
    - language: c # ubuntu xenial with python2 bindings
      os: linux
      dist: xenial
      install:
        - sudo apt-get install autoconf libtool pkg-config build-essential libjson-c-dev
        - sudo apt-get install python-dev python-cffi python-sklearn
      script:
        - ./bootstrap.sh
        - ./configure
        - make clean
        - make
        - python bindings/python/setup.py test
        - python bindings/python/example.py

    - language: c # ubuntu xenial with python3 bindings
      os: linux
      dist: xenial
      install:
        - sudo apt-get install autoconf libtool pkg-config build-essential libjson-c-dev
        - sudo apt-get install python3-dev python3-cffi python3-sklearn
      script:
        - ./bootstrap.sh
        - PYTHON=python3 ./configure
        - make clean
        - make
        - python3 bindings/python/setup.py test
        - python3 bindings/python/example.py

    - language: c # osx with python2 bindings
      os: osx
      install:
        - brew update
        - brew install json-c
        - pip install cffi sklearn
      script:
        - ./bootstrap.sh
        - ./configure
        - make clean
        - make
        - python bindings/python/setup.py test
        - python bindings/python/example.py
