matrix:
  include:
    - name: "Ubuntu 20.04"
      os: linux
      dist: focal
      language: c
      install:
        - "sudo apt-get install autoconf libtool build-essential python3-cffi python3-sklearn"
        - "python3 -m pip install catboost==0.25.1 xgboost==1.4.1 --user"
      script:
        - "./bootstrap.sh"
        - "PYTHON=python3 ./configure"
        - "make clean"
        - "make"
        - "python3 bindings/python/setup.py test"
        - "python3 bindings/python/example.py"

    - name: "macOS 11.3"
      os: osx
      osx_image: xcode12.5
      language: c
      install:
        - "brew install argp-standalone libomp"
        - "python3 -m pip install cffi sklearn catboost==0.25.1 xgboost==1.4.1 --user"
      script:
        - "./bootstrap.sh"
        - "PYTHON=python3 LDFLAGS=-largp ./configure"
        - "make clean"
        - "make"
        - "python3 bindings/python/setup.py test"
        - "python3 bindings/python/example.py"
