dist: xenial
language: c

install:
  - sudo apt-get install autoconf libtool pkg-config build-essential libjson-c-dev
  - sudo apt-get install python-dev python-cffi python-sklearn
  
script:
  - "./bootstrap.sh && ./configure && make clean && make"
  - python bindings/python/setup.py test
  - python bindings/python/example.py