matrix:
  include:
    - name: "Ubuntu 16.04 with Python 2 bindings"
      os: linux
      dist: xenial
      language: c
      install:
        - "sudo apt-get install autoconf libtool build-essential"
        - "sudo apt-get install python-cffi python-pip python-sklearn"
        - "python2 -m pip install catboost xgboost --user"
      script:
        - "./bootstrap.sh"
        - "PYTHON=python2 ./configure"
        - "make clean"
        - "make"
        - "python2 bindings/python/setup.py test"
        - "python2 bindings/python/example.py"

    - name: "Ubuntu 16.04 with Python 3 bindings"
      os: linux
      dist: xenial
      language: python
      python: "3.6"
      install:
        - "sudo apt-get install autoconf libtool build-essential"
        - "pip install cffi sklearn catboost xgboost"
      script:
        - "./bootstrap.sh"
        - "PYTHON=python3 ./configure"
        - "make clean"
        - "make"
        - "python3 bindings/python/setup.py test"
        - "python3 bindings/python/example.py"

    - name: "macOS 10 with Python 2 bindings"
      os: osx
      language: c
      install:
        - "pip install cffi sklearn catboost xgboost --user"
      script:
        - "./bootstrap.sh"
        - "./configure"
        - "make clean"
        - "make"
        - "python bindings/python/setup.py test"
        - "python bindings/python/example.py"
